name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-cf:
    runs-on: ubuntu-latest
    name: Deploy Cloudflare
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: { node-version: 16 }
      - uses: pnpm/action-setup@v2
        with: { version: 7, run_install: false }
      - run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
        id: pnpm-cache
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: production
      - name: Fix permissions borked by cloudflare/wrangler-action
        run: sudo chown -R $(id -un):$(id -gn) ${{ github.workspace }}
  deploy-deno:
    runs-on: ubuntu-latest
    name: Deploy Deno
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: { node-version: 16 }
      - uses: pnpm/action-setup@v2
        with: { version: 7, run_install: false }
      - run: echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
        id: pnpm-cache
      - uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install
      - run: rm -r node_modules
      - uses: denoland/deployctl@v1
        with:
          project: worker-news
          entrypoint: src/entry/deno.ts
          import-map: import-map.json
      